version: '3.8'
services:
  neo4j:
    restart: unless-stopped
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_PLUGINS: '["graph-data-science"]'
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/conf:/var/lib/neo4j/conf
