version: '3.8'
services:
  db:
    restart: always
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/shad-networks
    volumes:
      - neo4j_data:/data
  server:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  neo4j_data:
