version: '3.8'
services:
  db:
    restart: always
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/shad-networks
      NEO4J_PLUGINS: '["graph-data-science"]'
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - neo4j_data:/data
  server:
    build: ./
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  neo4j_data:
