// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	neo4j "github.com/neo4j/neo4j-go-driver/v5/neo4j"
	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockGraphDbDriver is a mock of GraphDbDriver interface.
type MockGraphDbDriver struct {
	ctrl     *gomock.Controller
	recorder *MockGraphDbDriverMockRecorder
	isgomock struct{}
}

// MockGraphDbDriverMockRecorder is the mock recorder for MockGraphDbDriver.
type MockGraphDbDriverMockRecorder struct {
	mock *MockGraphDbDriver
}

// NewMockGraphDbDriver creates a new mock instance.
func NewMockGraphDbDriver(ctrl *gomock.Controller) *MockGraphDbDriver {
	mock := &MockGraphDbDriver{ctrl: ctrl}
	mock.recorder = &MockGraphDbDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphDbDriver) EXPECT() *MockGraphDbDriverMockRecorder {
	return m.recorder
}

// NewSession mocks base method.
func (m *MockGraphDbDriver) NewSession(ctx context.Context, config neo4j.SessionConfig) Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", ctx, config)
	ret0, _ := ret[0].(Session)
	return ret0
}

// NewSession indicates an expected call of NewSession.
func (mr *MockGraphDbDriverMockRecorder) NewSession(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockGraphDbDriver)(nil).NewSession), ctx, config)
}

// Unwrap mocks base method.
func (m *MockGraphDbDriver) Unwrap() neo4j.DriverWithContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unwrap")
	ret0, _ := ret[0].(neo4j.DriverWithContext)
	return ret0
}

// Unwrap indicates an expected call of Unwrap.
func (mr *MockGraphDbDriverMockRecorder) Unwrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unwrap", reflect.TypeOf((*MockGraphDbDriver)(nil).Unwrap))
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSession) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSession)(nil).Close), ctx)
}

// ExecuteWrite mocks base method.
func (m *MockSession) ExecuteWrite(ctx context.Context, work neo4j.ManagedTransactionWork, configurers ...func(*neo4j.TransactionConfig)) (any, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, work}
	for _, a := range configurers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteWrite", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWrite indicates an expected call of ExecuteWrite.
func (mr *MockSessionMockRecorder) ExecuteWrite(ctx, work any, configurers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, work}, configurers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWrite", reflect.TypeOf((*MockSession)(nil).ExecuteWrite), varargs...)
}

// MockCacheDriver is a mock of CacheDriver interface.
type MockCacheDriver struct {
	ctrl     *gomock.Controller
	recorder *MockCacheDriverMockRecorder
	isgomock struct{}
}

// MockCacheDriverMockRecorder is the mock recorder for MockCacheDriver.
type MockCacheDriverMockRecorder struct {
	mock *MockCacheDriver
}

// NewMockCacheDriver creates a new mock instance.
func NewMockCacheDriver(ctrl *gomock.Controller) *MockCacheDriver {
	mock := &MockCacheDriver{ctrl: ctrl}
	mock.recorder = &MockCacheDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheDriver) EXPECT() *MockCacheDriverMockRecorder {
	return m.recorder
}

// Unwrap mocks base method.
func (m *MockCacheDriver) Unwrap() *redis.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unwrap")
	ret0, _ := ret[0].(*redis.Client)
	return ret0
}

// Unwrap indicates an expected call of Unwrap.
func (mr *MockCacheDriverMockRecorder) Unwrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unwrap", reflect.TypeOf((*MockCacheDriver)(nil).Unwrap))
}
